project_id = "plxsenykjisqutxcvjeg"

[functions.songwriter-career-summary]
verify_jwt = false

[functions.generate-payout-statement]
verify_jwt = true

[functions.generate-bulk-statements]
verify_jwt = true

[functions.docusign-import]
verify_jwt = true

[functions.docusign-send]
verify_jwt = true